### ISSUE TITLE
Rapids is failing to init Jupyter and Dask isn't started

### ISSUE THREAD

**Issue by ChethanUK** [GoogleCloudDataproc/initialization-actions#611]
Jupyter is not getting started:
```bash
cat /var/log/jupyter_notebook.log
[D 11:23:46.051 NotebookApp] [nb_conda_kernels] refreshing conda info
[E 11:23:46.056 NotebookApp] [nb_conda_kernels] couldn't call conda:
    [Errno 2] No such file or directory
[I 11:23:46.057 NotebookApp] [nb_conda_kernels] enabled, 0 kernels found
Traceback (most recent call last):
  File "/opt/conda/anaconda/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/anaconda/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</opt/conda/anaconda/lib/python2.7/site-packages/decorator.pyc:decorator-gen-7>", line 2, in initialize
  File "/opt/conda/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/anaconda/lib/python2.7/site-packages/notebook/notebookapp.py", line 1630, in initialize
    self.init_webapp()
  File "/opt/conda/anaconda/lib/python2.7/site-packages/notebook/notebookapp.py", line 1378, in init_webapp
    self.jinja_environment_options,
  File "/opt/conda/anaconda/lib/python2.7/site-packages/notebook/notebookapp.py", line 159, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/opt/conda/anaconda/lib/python2.7/site-packages/notebook/notebookapp.py", line 252, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/opt/conda/anaconda/lib/python2.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/conda/anaconda/lib/python2.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/anaconda/lib/python2.7/site-packages/notebook/notebookapp.py", line 867, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known
```

Dask is not getting started:
```bash
/tmp/rapids-init-action-eNh7/internal/launch-dask.sh: line 17: /usr/local/bin/launch-dask.sh: 
Permission denied
```

Issuse with Dask Import:
```bash
cat /var/log/dask-cuda-workers.log
Traceback (most recent call last):
  File "/opt/conda/anaconda/envs/RAPIDS/bin/dask-cuda-worker", line 11, in <module>
    load_entry_point('dask-cudf==0.7.0', 'console_scripts', 'dask-cuda-worker')()
  File "/opt/conda/anaconda/envs/RAPIDS/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/conda/anaconda/envs/RAPIDS/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/opt/conda/anaconda/envs/RAPIDS/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/opt/conda/anaconda/envs/RAPIDS/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/conda/anaconda/envs/RAPIDS/lib/python3.7/site-packages/dask_cuda/dask_cuda_worker.py", line 12, in <module>
    from distributed.worker import _ncores
ImportError: cannot import name '_ncores' from 'distributed.worker' (/opt/conda/anaconda/envs/RAPIDS/lib/python3.7/site-packages/distributed/worker.py)
```

**Comment by aroraakshit** [comment]
Facing the same issue.

**Comment by aroraakshit** [comment]
Facing the same issue. Log files attached.

[google-cloud-dataproc-metainfo_d7b72874-b8ac-4413-96ae-874d3a31f091_akshita-rapids-nyctaxi1-m_dataproc-initialization-script-0_output.txt](https://github.com/GoogleCloudDataproc/initialization-actions/files/4162774/google-cloud-dataproc-metainfo_d7b72874-b8ac-4413-96ae-874d3a31f091_akshita-rapids-nyctaxi1-m_dataproc-initialization-script-0_output.txt)
[google-cloud-dataproc-metainfo_d7b72874-b8ac-4413-96ae-874d3a31f091_akshita-rapids-nyctaxi1-m_dataproc-startup-script_output.txt](https://github.com/GoogleCloudDataproc/initialization-actions/files/4162775/google-cloud-dataproc-metainfo_d7b72874-b8ac-4413-96ae-874d3a31f091_akshita-rapids-nyctaxi1-m_dataproc-startup-script_output.txt)

**Comment by medb** [comment]
@aroraakshit how did you create a cluster? Did you try to use the latest version of RAPIDS init actions from GitHub repo?

**Comment by aroraakshit** [comment]
Here is how I created the cluster:
```
CLUSTER_NAME=akshita-rapids-nyctaxi1
REGION=global
STORAGE_BUCKET=aa_xgb_rapids_spark_sample
NUM_GPUS_IN_MASTER=4
NUM_GPUS_IN_WORKER=4
NUM_WORKERS=2
DATAPROC_BUCKET=dataproc-initialization-actions
gcloud beta dataproc clusters create $CLUSTER_NAME  \
--region $REGION \
--master-accelerator type=nvidia-tesla-t4,count=$NUM_GPUS_IN_MASTER \
--master-machine-type n1-standard-32 \
--worker-accelerator type=nvidia-tesla-t4,count=$NUM_GPUS_IN_WORKER \
--worker-machine-type n1-standard-32 \
--num-workers $NUM_WORKERS \
--bucket $STORAGE_BUCKET \
--metadata "JUPYTER_PORT=8888" \
--initialization-actions gs://$DATAPROC_BUCKET/rapids/rapids.sh \
--optional-components=ANACONDA,JUPYTER \
--enable-component-gateway
```
I assume `$DATAPROC_BUCKET (dataproc-initialization-actions)` has the latest version of RAPIDS init action from this repository.

**Comment by medb** [comment]
I just tried to create cluster with init actions in GCS buckets and it succeeded:

```bash
CLUSTER_NAME=<cluster-name>
REGION=<region>
gcloud dataproc clusters create ${CLUSTER_NAME} \
    --image-version=1.3 \
    --region=${REGION} \
    --master-accelerator=type=nvidia-tesla-p100 \
    --worker-accelerator=type=nvidia-tesla-p100 \
    --optional-components=ANACONDA,JUPYTER \
    --initialization-actions=gs://goog-dataproc-initialization-actions-${REGION}/gpu/install_gpu_driver.sh,gs://goog-dataproc-initialization-actions-${REGION}/rapids/rapids.sh \
    --initialization-action-timeout=30m \
    --metadata=gpu-driver-provider=NVIDIA
```

**Comment by aroraakshit** [comment]
1.4-debian9 version works. 1.3 does not. 
```
CLUSTER_NAME=<cluster-name>
STORAGE_BUCKET=<bucket-name>
NUM_WORKERS=2
REGION=us-central1
gcloud beta dataproc clusters create ${CLUSTER_NAME} \
    --image-version=1.4 \
    --region=${REGION} \
    --master-accelerator=type=nvidia-tesla-t4 \
    --worker-accelerator=type=nvidia-tesla-t4,count=4 \
    --num-workers $NUM_WORKERS \
    --bucket $STORAGE_BUCKET \
    --optional-components=ANACONDA,JUPYTER \
    --initialization-actions=gs://goog-dataproc-initialization-actions-${REGION}/rapids/rapids.sh \
    --initialization-action-timeout=30m \
    --metadata=gpu-driver-provider=NVIDIA \
    --metadata "JUPYTER_PORT=8888" \
    --enable-component-gateway
```

**Comment by medb** [comment]
@aroraakshit, you didn't include GPU init action in your command and specified `1.4` version instead of `1.3` version.

This command works with latest init actions (you need to deploy them manually to GCS, because we didn't release latest versions of init actions from GitHub to GCS yet):

```bash
gcloud beta dataproc clusters create ${CLUSTER_NAME} \
    --image-version 1.3 \
    --region ${REGION} \
    --master-accelerator type=nvidia-tesla-t4 \
    --worker-accelerator type=nvidia-tesla-t4,count=4 \
    --num-workers $NUM_WORKERS \
    --optional-components ANACONDA,JUPYTER \
    --initialization-actions gs://${BUCKET}/gpu/install_gpu_driver.sh,gs://${BUCKET}/rapids/rapids.sh \
    --initialization-action-timeout 30m \
    --metadata gpu-driver-provider=NVIDIA \
    --metadata JUPYTER_PORT=8888 \
    --enable-component-gateway
```
