### ISSUE TITLE
Apache Ranger Errors

### ISSUE THREAD

**Issue by ChethanUK** [GoogleCloudDataproc/initialization-actions#656]
First of all this error: https://issues.apache.org/jira/projects/RANGER/issues/RANGER-2593

Then these: 

1. 
```bash
Starting configuration for Ranger DB credentials:
Using Java:/usr/lib/jvm/java-8-openjdk-amd64/bin/java
Error creating Alias!! Error: Exception in thread "main" java.lang.NoClassDefFoundError: com/ctc/wstx/io/InputBootstrapper
	at org.apache.ranger.credentialapi.CredentialReader.getDecryptedString(CredentialReader.java:38)
	at org.apache.ranger.credentialapi.buildks.createCredential(buildks.java:80)
	at org.apache.ranger.credentialapi.buildks.main(buildks.java:40)
Caused by: java.lang.ClassNotFoundException: com.ctc.wstx.io.InputBootstrapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

Using Java:/usr/lib/jvm/java-8-openjdk-amd64/bin/java
Error creating Alias!! Error: Exception in thread "main" java.lang.NoClassDefFoundError: com/ctc/wstx/io/InputBootstrapper
	at org.apache.ranger.credentialapi.CredentialReader.getDecryptedString(CredentialReader.java:38)
	at org.apache.ranger.credentialapi.buildks.createCredential(buildks.java:80)
	at org.apache.ranger.credentialapi.buildks.main(buildks.java:40)
Caused by: java.lang.ClassNotFoundException: com.ctc.wstx.io.InputBootstrapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

Using Java:/usr/lib/jvm/java-8-openjdk-amd64/bin/java
Error creating Alias!! Error: Exception in thread "main" java.lang.NoClassDefFoundError: com/ctc/wstx/io/InputBootstrapper
	at org.apache.ranger.credentialapi.CredentialReader.getDecryptedString(CredentialReader.java:38)
	at org.apache.ranger.credentialapi.buildks.createCredential(buildks.java:80)
	at org.apache.ranger.credentialapi.buildks.main(buildks.java:40)
Caused by: java.lang.ClassNotFoundException: com.ctc.wstx.io.InputBootstrapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

2. 
```bash
+ Fri Oct 18 18:10:07 UTC 2019 : Saving current config file: /usr/lib/ranger/hive/conf/ranger-policymgr-ssl.xml to /usr/lib/ranger/hive/conf/.ranger-policymgr-ssl.xml.20191018-181006 ...
Unable to store password in non-plain text format. Error: [Exception in thread "main" java.lang.NoClassDefFoundError: com/ctc/wstx/io/InputBootstrapper
	at org.apache.ranger.credentialapi.CredentialReader.getDecryptedString(CredentialReader.java:38)
	at org.apache.ranger.credentialapi.buildks.createCredential(buildks.java:80)
	at org.apache.ranger.credentialapi.buildks.main(buildks.java:40)
Caused by: java.lang.ClassNotFoundException: com.ctc.wstx.io.InputBootstrapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more]
Exiting plugin installation
```

3. Hive-Dataproc Ranger plugin is not working: 
```bash
Connection Failed. Unable to retrieve any files using given parameters, You can still save the repository and start creating policies, but you would not be able to use autocomplete for resource names. Check ranger_admin.log for more info.
```

**Comment by medb** [comment]
Apache Ranger initialization action was deprecated in favor of [Ranger Component](https://cloud.google.com/dataproc/docs/concepts/components/ranger).
