### ISSUE TITLE
CI failed with "No module named 'absl'"

### ISSUE THREAD

**Issue by functicons** [GoogleCloudDataproc/initialization-actions#728]
```
======================================================================
ERROR: test_h2o (fastunit.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_h2o
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fastunit-0.0.1-py3.5.egg/fastunit/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/init-actions/h2o/test_h2o.py", line 9, in <module>
    from integration_tests.dataproc_test_case import DataprocTestCase
  File "/init-actions/integration_tests/dataproc_test_case.py", line 13, in <module>
    from absl import flags
ImportError: No module named 'absl'
```

**Comment by functicons** [comment]
It seems to be caused by the PR didn't rebase to the HEAD, the `install_test_dependencies` has long been removed in https://github.com/GoogleCloudDataproc/initialization-actions/commit/3bda87841a51c781ad44d726d2bcb4a5b0ed7920#diff-7ae33138f61fb3d1e8bb5641f5fea3a1
