### ISSUE TITLE
Spark 3.0 Horovod training fails with HDSF error

### ISSUE THREAD

**Issue by arunraman** [GoogleCloudDataproc/initialization-actions#779]
I have a Dataproc cluster with the following image: `2.0.0-RC1-ubuntu18`

I modified an example from the Horovod Spark: https://github.com/horovod/horovod/blob/master/examples/keras_spark_rossmann_estimator.py

I am hitting the following error on this line:

```
keras_model = keras_estimator.fit(train_df).setOutputCols(['Sales'])
```

Error:
```
hdfsExists: invokeMethod((Lorg/apache/hadoop/fs/Path;)Z) error:
java.lang.ClassCastException: org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto cannot be cast to com.google.protobuf.Message
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:118)
	at com.sun.proxy.$Proxy9.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:907)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy10.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1666)
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1576)
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1573)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1588)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1683)
Traceback (most recent call last):
  File "/tmp/537ae15236734a5c8b9e60faac43c629/sparkjob1.py", line 335, in <module>
    keras_model = keras_estimator.fit(train_df).setOutputCols(['Sales'])
  File "/opt/conda/default/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 37, in fit
    return super(HorovodEstimator, self).fit(df, params)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/base.py", line 129, in fit
  File "/opt/conda/default/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 78, in _fit
    verbose=self.getVerbose()) as dataset_idx:
  File "/opt/conda/default/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/conda/default/lib/python3.7/site-packages/horovod/spark/common/util.py", line 636, in prepare_data
    num_partitions, num_processes, verbose)
  File "/opt/conda/default/lib/python3.7/site-packages/horovod/spark/common/util.py", line 572, in _get_or_create_dataset
    store, label_columns, feature_columns, sample_weight_col, dataset_idx)
  File "/opt/conda/default/lib/python3.7/site-packages/horovod/spark/common/util.py", line 413, in get_simple_meta_from_parquet
    raise ValueError("{} path does not exist in the store".format(train_data_path))
ValueError: hdfs:///tmp/horovod/intermediate_train_data.0 path does not exist in the store
```

Even though I can see the files available in the HDFS:

```
$ hadoop  fs -ls /tmp/horovod/intermediate_train_data.0
Found 17 items
-rw-r--r--   2 root hadoop          0 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/_SUCCESS
-rw-r--r--   2 root hadoop    1027422 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00000-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1021719 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00001-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1025107 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00002-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1019034 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00003-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1024424 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00004-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1021981 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00005-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1023346 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00006-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1021876 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00007-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1024823 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00008-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1026777 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00009-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1033677 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00010-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1034280 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00011-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1026418 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00012-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1026736 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00013-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1033822 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00014-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
-rw-r--r--   2 root hadoop    1025689 2020-07-09 23:06 /tmp/horovod/intermediate_train_data.0/part-00015-68deff3e-931a-48a2-8b0f-930754880b8c-c000.snappy.parquet
```

The raw data is coming from the GCS.

**Comment by arunraman** [comment]
Thanks, where should I set this. This is where the HVD starts training

`keras_model = keras_estimator.fit(train_df).setOutputCols(['Sales'])`

The MPI run is triggered using this. In this how where do I set the classpath?

**Comment by arunraman** [comment]
@medb Any idea how this can be done?

**Comment by roarjn** [comment]
When specifying GCS path in https://github.com/horovod/horovod/blob/master/examples/keras_spark_rossmann_estimator.py#L366 
```
   store = Store.create("gs://gcs-bucket")
#    store = Store.create("hdfs:///tmp/horovod")
    keras_estimator = hvd.KerasEstimator(num_proc=2,
                                        model=model,
                                        store=store,
                                        optimizer=opt,
                                        loss='mae',
                                        metrics=[exp_rmspe],
                                        custom_objects=CUSTOM_OBJECTS,
                                        feature_cols=all_cols,
                                        label_cols=['Sales'],
                                        validation='Validation',
                                        batch_size=1000,
                                        epochs=5,
                                        verbose=0)
```
fails with error message:
```
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 936, in parquet
  File "/usr/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 102, in deco
pyspark.sql.utils.IllegalArgumentException: Wrong FS: file://gs:/gcs-bucket/intermediate_train_data.0, expected: file:///
ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [9317119696b94e6398fc6ab4fbae3a49] failed with error:
Job failed with message [pyspark.sql.utils.IllegalArgumentException: Wrong FS: file://gs:/gcs-bucket/intermediate_train_data.0
```

**Comment by medb** [comment]
@arunraman I'm not familiar with Horovod so can not help, maybe it worth to files issue for them and they will be able to help.

**Comment by medb** [comment]
@roarjn Seems like Horovod does not support GCS or any other HCFS filesystems except HDFS:
https://github.com/horovod/horovod/blob/1104a5fe8f716976e4794b7c365c95524b458e4a/horovod/spark/common/store.py#L33

**Comment by arunraman** [comment]
I just checked with the Horovod issue, 

https://github.com/horovod/horovod/issues/2093

it looks like a compatibility issue between the protobuff from google and Hadoop. 

`hdfsExists: invokeMethod((Lorg/apache/hadoop/fs/Path;)Z) error:
ClassCastException: org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto cannot be cast to com.google.protobuf.Messagejava.lang.ClassCastException: org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto cannot be cast to com.google.protobuf.Message
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:118)
        at com.sun.proxy.$Proxy9.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:907)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
        at com.sun.proxy.$Proxy10.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1666)
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1576)
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1573)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1588)
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1683)
Traceback (most recent call last):
  File "/tmp/d28ed9e680744356ae0fa4909972b2da/sparkJobEstimator.py", line 335, in <module>
    keras_model = keras_estimator.fit(train_df).setOutputCols(['Sales'])
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 37, in fit
    return super(HorovodEstimator, self).fit(df, params)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/base.py", line 129, in fit
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/estimator.py", line 78, in _fit
    verbose=self.getVerbose()) as dataset_idx:
  File "/opt/conda/default/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/util.py", line 636, in prepare_data
    num_partitions, num_processes, verbose)
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/util.py", line 572, in _get_or_create_dataset
    store, label_columns, feature_columns, sample_weight_col, dataset_idx)
  File "/root/.local/lib/python3.7/site-packages/horovod/spark/common/util.py", line 413, in get_simple_meta_from_parquet
    raise ValueError("{} path does not exist in the store".format(train_data_path))
ValueError: hdfs:///tmp/horovod/intermediate_train_data.0 path does not exist in the store
ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [d28ed9e680744356ae0fa4909972b2da] failed with error:
`

**Comment by medb** [comment]
Yeah, the question is why Horovod brings in Protobuf library. Is it installs it as part of PySpark client?

Because when you SSH in Dataproc cluster and search for all Protobuf jars, all of them have the same 2.5.0 version:
```bash
$ gcloud compute ssh $CLUSTER_NAME --command "find / -name proto*.jar 2>/dev/null"
/usr/lib/hadoop-hdfs/lib/protobuf-java-2.5.0.jar
/usr/lib/tez/lib/protobuf-java-2.5.0.jar
/usr/lib/hadoop/lib/protobuf-java-2.5.0.jar
/usr/lib/pig/lib/protobuf-java-2.5.0.jar
/usr/lib/hive/lib/protobuf-java-2.5.0.jar
/usr/lib/spark/jars/protobuf-java-2.5.0.jar
```

**Comment by bradmiro** [comment]
@arunraman did you end up finding a solution here?

**Comment by bradmiro** [comment]
@medb we can close this re: https://github.com/GoogleCloudDataproc/initialization-actions/pull/858
