### ISSUE TITLE
GPU and Rapid error - Could not initialize class ml.dmlc.xgboost4j.java.XGBoostSparkJNI

### ISSUE THREAD

**Issue by tfayyaz** [GoogleCloudDataproc/initialization-actions#791]
When I train the model using GPUs from the notebook https://github.com/NVIDIA/spark-xgboost-examples/blob/spark-2/examples/notebooks/python/mortgage-gpu.ipynb it fails and the following error appears in the spark history server.

```
Job aborted due to stage failure: Task 0 in stage 2.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2.0 (TID 5, jupyter-gpu-cluster-1-4-v4-w-1.us-central1-f.c.datalake-demo-admin.internal, executor 2): java.lang.NoClassDefFoundError: Could not initialize class ml.dmlc.xgboost4j.java.XGBoostSparkJNI
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$appendGpuIdToParameters(XGBoost.scala:585)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$ml$dmlc$xgboost4j$scala$spark$XGBoost$$trainForGpuDataset$1.apply(XGBoost.scala:614)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$ml$dmlc$xgboost4j$scala$spark$XGBoost$$trainForGpuDataset$1.apply(XGBoost.scala:613)
	at ml.dmlc.xgboost4j.scala.spark.rapids.GpuDataset$$anonfun$ml$dmlc$xgboost4j$scala$spark$rapids$GpuDataset$$getBatchMapper$1.apply(GpuDataset.scala:487)
	at ml.dmlc.xgboost4j.scala.spark.rapids.GpuDataset$$anonfun$ml$dmlc$xgboost4j$scala$spark$rapids$GpuDataset$$getBatchMapper$1.apply(GpuDataset.scala:486)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:823)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:823)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:359)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:357)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1165)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1156)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1091)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1156)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:882)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:357)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:308)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I believe this might be due to the cuda versions. The GPU init action has a default of 10.1 and the Rapids init action has a default of 10.2.

If I manually set `--metadata cuda-version=10.1` when creating the cluster then this resolves the issue. I need to test if setting `--metadata cuda-version=10.2` also resolves the issue.

**Comment by bradmiro** [comment]
@mengdong does CUDA 10.2 not work with Spark-RAPIDS 2.x?

**Comment by mengdong** [comment]
Looks like https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/rapids/rapids.sh#L13-L23 set cuda to 10.1 for spark2.x. This conflicts with gpu init script which use 10.2 as default. 

XGBoost work with cuda 10.2. I think cudf 0.9.2 doesn't have a 10.2 build. Could we make a note in the README to clarify? To let the user use `--metadata cuda-version=10.1` @tfayyaz suggested

on NVIDIA side, we are mainly focus on spark3 now, I don't think cudf will be upgraded for spark 2.x

**Comment by bradmiro** [comment]
Thanks @mengdong for clarifying and @tfayyaz for pointing this out. I'll update the README.

**Comment by tfayyaz** [comment]
Just a few other things I noticed:

On line 36/37 of the GPU init action it has the following:

```bash
readonly DEFAULT_NVIDIA_DEBIAN_CUDA_URL='http://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda_10.2.89_440.33.01_linux.run'
readonly NVIDIA_DEBIAN_CUDA_URL=$(get_metadata_attribute 'cuda-url' "${DEFAULT_NVIDIA_DEBIAN_CUDA_URL}")
```

So even I set metadata cuda-version to 10.1 it will still use that default URL that has 10.2. If a user is going to set this manually is there a link to a webpage where you can find the correct URL?

Also in the README.md file it incorrectly has cuda-url twice under *Supported metadata parameters:*. The 2nd one should be cuda-version. I'll create a pull request for that.

**Comment by tfayyaz** [comment]
I tested with cuda-version=10.0 and the cluster fails to create and I get the error message "Cannot find 10.0 cuda version" in the logs.

**Comment by mengdong** [comment]
Yep, that is valid issue, the cuda 10.1 installer is here `http://developer.download.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.243_418.87.00_linux.run`

**Comment by mengdong** [comment]
We should consider drop 10.0 as that is super out-dated. Spark rapids in spark 3 doesn't support 10.0

**Comment by bradmiro** [comment]
@mengdong Are there separate CUDA links for 10.1 vs 10.2 for Ubuntu? That URL schema seems to line up with the Debian drivers in the init action.

**Comment by mengdong** [comment]
for ubuntu we don't have install through a URL run file. only for debian
