### ISSUE TITLE
Issue specifying `db-hive-password` for connection from hive service to cloud sql instance

### ISSUE THREAD

**Issue by AntJW** [GoogleCloudDataproc/initialization-actions#889]
Hi,

When creating a dataproc cluster with the `db-hive-password` metadata value specified, the cluster create fails (see error below). Specifying this metadata value worked previously.

Command:
```
gcloud dataproc clusters create $USER-metastore-service-foo-555  \
    --scopes cloud-platform \
    --image-version 2.0.4-debian10 \
    --project foo-project \
    --region us-central1 \
    --initialization-actions gs://goog-dataproc-initialization-actions-us-central1/cloud-sql-proxy/cloud-sql-proxy.sh \
    --properties="hive:hive.metastore.warehouse.dir=gs://foo-bucket/default,spark:spark.sql.sources.partitionOverwriteMode=dynamic" \
    --metadata "hive-metastore-instance=etsy-hadoop-sandbox-dev:us-central1:metastore-database" \
    --metadata "kms-key-uri=projects/[PROJECT]/locations/us-central1/keyRings/[RING]/cryptoKeys/[KEY]" \
    --metadata "db-hive-user=hive" \
    --metadata "db-hive-password-uri=gs://foo-config/hive-admin-password.encrypted"
```

Error:
```
Synchronizing state of mysql.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable mysql
Removed /etc/systemd/system/multi-user.target.wants/mysql.service.
2021-03-18 23:46:33 URL:https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 [14850063/14850063] -> "cloud_sql_proxy.linux.amd64" [1]
Created symlink /etc/systemd/system/multi-user.target.wants/cloud-sql-proxy.service → /lib/systemd/system/cloud-sql-proxy.service.
About to run 'nc -zv localhost 3306' with retries...
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 1 failed! Sleeping 1.
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 2 failed! Sleeping 1.
nc: connect to localhost port 3306 (tcp) failed: Connection refused
Connection to localhost 3306 port [tcp/mysql] succeeded!
Cloud SQL Proxy installation succeeded
Logs can be found in /var/log/cloud-sql-proxy/cloud-sql-proxy.log
Traceback (most recent call last):
  File "/usr/local/share/google/bdconfig/lib/google_hadoop/bdconfig_lib/bdconfig.py", line 59, in <module>
    appcommands.Run()
  File "/usr/local/share/google/bdconfig/lib/pyglib/google/apputils/appcommands.py", line 769, in Run
    return app.run()
  File "/usr/local/share/google/bdconfig/lib/pyglib/google/apputils/app.py", line 216, in run
    return _actual_start()
  File "/usr/local/share/google/bdconfig/lib/pyglib/google/apputils/app.py", line 244, in _actual_start
    really_start()
  File "/usr/local/share/google/bdconfig/lib/pyglib/google/apputils/appcommands.py", line 755, in _CommandsStart
    sys.exit(command.CommandRun(GetCommandArgv()))
  File "/usr/local/share/google/bdconfig/lib/pyglib/google/apputils/appcommands.py", line 283, in CommandRun
    ret = self.Run(argv)
  File "/usr/local/share/google/bdconfig/lib/google_hadoop/bdconfig_lib/xml_config_commands.py", line 224, in Run
    self._flags.source_configuration_file)
  File "/usr/local/share/google/bdconfig/lib/google_hadoop/bdconfig_lib/xml_configuration.py", line 192, in FromFile
    document = minidom.parse(file)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1918, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 924, in parse
    result = builder.parseFile(fp)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 14, column 19
****
```

**Comment by AntJW** [comment]
I figured out the issue. My password had an ampersand (&) in it, which is not compatible within a xml file (hive-site.xml) property value (javax.jdo.option.ConnectionPassword). I changed the password and removed the ampersand from it, now it is connecting as expected. I will go ahead and resolve this ticket. However, it might be worth it to add a password validator in the cloud-sql-proxy.sh init script checking for ampersands, because the error does not make it immediately clear what the issue is.
