### ISSUE TITLE
Add support for Oozie on a CentOS cluster

### ISSUE THREAD

**Issue by sshetty007** [GoogleCloudDataproc/initialization-actions#944]
The initialization action currently does not install the necessary packages on CentOS.

Installing packages via `dnf` still has the issue of not starting the Oozie EmbeddedServer properly.

Please add support for Oozie on a CentOS cluster.

**Comment by medb** [comment]
What version of Dataproc CentOS image do you use?

**Comment by sshetty007** [comment]
We have tried this with 2.0-centos and 1.5.48-centos

**Comment by sshetty007** [comment]
I have submitted a PR to include CentOS support. Please review and let met me know if any changes are required.
https://github.com/GoogleCloudDataproc/initialization-actions/pull/948

**Comment by suchchal** [comment]
> I have submitted a PR to include CentOS support. Please review and let met me know if any changes are required. #948

I am running updated oozie.sh which supports CentOS cluster. Although it is able to install Oozie and Oozie client, it is throwing below error at the end while running ooziedb.sh:-

+ sudo -u oozie /usr/lib/oozie/bin/ooziedb.sh create -run
  setting OOZIE_DATA=/var/lib/oozie
  setting JETTY_PID_FILE=/var/run/oozie/oozie.pid
  setting OOZIE_CONFIG=/etc/oozie/conf
  setting OOZIE_LOG=/var/log/oozie
  setting OOZIE_DATA=/var/lib/oozie
  setting JETTY_PID_FILE=/var/run/oozie/oozie.pid
  setting OOZIE_CONFIG=/etc/oozie/conf
  setting OOZIE_LOG=/var/log/oozie

Validate DB Connection
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/util/ReflectionUtils
        at org.apache.oozie.service.Services.setServiceInternal(Services.java:378)
        at org.apache.oozie.service.Services.<init>(Services.java:111)
        at org.apache.oozie.tools.OozieDBCLI.getJdbcConf(OozieDBCLI.java:173)
        at org.apache.oozie.tools.OozieDBCLI.createConnection(OozieDBCLI.java:915)
        at org.apache.oozie.tools.OozieDBCLI.validateConnection(OozieDBCLI.java:923)
        at org.apache.oozie.tools.OozieDBCLI.createDB(OozieDBCLI.java:192)
        at org.apache.oozie.tools.OozieDBCLI.run(OozieDBCLI.java:135)
        at org.apache.oozie.tools.OozieDBCLI.main(OozieDBCLI.java:83)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.util.ReflectionUtils
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 8 more

Please suggest the solution.

**Comment by medb** [comment]
Seems like Oozie is missing either `hadoop-common` or `hadoop-client-api` jars in your set up: https://search.maven.org/search?q=fc:org.apache.hadoop.util.ReflectionUtils%20AND%20v:3.2.2
