### ISSUE TITLE
I see this error in jupyter components using the jupyter initialzation action

### ISSUE THREAD

**Issue by ns-shua** [GoogleCloudDataproc/initialization-actions#980]
[E 17:13:46.656 NotebookApp] Uncaught exception GET /notebooks/data-qe-dataproc-staging/notebooks/Untitled.ipynb?kernel_name=pyspark (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8123', method='GET', uri='/notebooks/data-qe-dataproc-staging/notebooks/Untitled.ipynb?kernel_name=pyspark', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 775, in run
        yielded = self.gen.send(value)
      File "/opt/conda/lib/python3.7/site-packages/notebook/notebook/handlers.py", line 101, in get
        get_frontend_exporters=get_frontend_exporters
      File "/opt/conda/lib/python3.7/site-packages/notebook/base/handlers.py", line 516, in render_template
        return template.render(**ns)
      File "/opt/conda/lib/python3.7/site-packages/jinja2/environment.py", line 1291, in render
        self.environment.handle_exception()
      File "/opt/conda/lib/python3.7/site-packages/jinja2/environment.py", line 926, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "/opt/conda/lib/python3.7/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/opt/conda/lib/python3.7/site-packages/notebook/templates/page.html", line 154, in top-level template code
        {% block header %}
      File "/opt/conda/lib/python3.7/site-packages/notebook/templates/notebook.html", line 115, in block 'header'
        {% for exporter in get_frontend_exporters() %}
      File "/opt/conda/lib/python3.7/site-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "/opt/conda/lib/python3.7/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/__init__.py", line 4, in <module>
        from .slides import SlidesExporter
      File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/slides.py", line 12, in <module>
        from ..preprocessors.base import Preprocessor
      File "/opt/conda/lib/python3.7/site-packages/nbconvert/preprocessors/__init__.py", line 10, in <module>
        from .execute import ExecutePreprocessor
      File "/opt/conda/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 7, in <module>
        from nbclient import NotebookClient, execute as _execute
      File "/opt/conda/lib/python3.7/site-packages/nbclient/__init__.py", line 6, in <module>
        from .client import NotebookClient, execute  # noqa: F401
      File "/opt/conda/lib/python3.7/site-packages/nbclient/client.py", line 18, in <module>
        from traitlets import (
    ImportError: cannot import name 'Callable' from 'traitlets' (/opt/conda/lib/python3.7/site-packages/traitlets/__init__.py)

**Comment by medb** [comment]
Jupyter initialization action is deprecated, please use Jupyter component instead: https://cloud.google.com/dataproc/docs/concepts/components/jupyter
